export const colors = {
  primary: '#01D167',
  secondary: '#0C365A',
  inactiveTab: '#DDDDDD',
  lightGray: '#DCDCDC',
  disabledButton: '#EEEEEE',
  gray: 'gray',
  red: 'red',
  black: 'black',
  green: 'green',
  white: 'white',
  transparent: 'transparent',
  lightBlue: 'lightblue',
  lightGreen: '#E5FAF0',
  inputTextColor: '#222222',
  layoutLevel1: '#FFFFFF',
  layoutLevel2: '#EEEEEE',
  defaultLabel1: '#FFFFFF',
  defaultLabel2: '#25345F',
  pTextColor: '#222222',
};
